### ISSUE TITLE
Loading more data

### ISSUE THREAD

**Issue by vkbrad** [GriddleGriddle/griddle-position-plugin#2]
I'm trying to implement infinite scrolling with some fetch function using this plugin. I was wondering if there is an easy way to tell when the last row is visible or the scroll bar has reached the bottom of the page?

**Comment by ryanlanciaux** [comment]
Were you able to figure this out? Does https://github.com/GriddleGriddle/griddle-remote-plugin handle that use case by chance?

**Comment by vkbrad** [comment]
Yeah I started looking at how that plugin works and it looks like it does exactly what I need so I figured I would close the issue. Thanks!
