### ISSUE TITLE
Breaks column width on fixed tables

### ISSUE THREAD

**Issue by cazzer** [GriddleGriddle/griddle-position-plugin#3]
When using this plugin, the data-table no longer respects `width` set on `ColumnDefinition`. This may be due to the spacer row not having any columns.

**Comment by cazzer** [comment]
Here's a shot of what I'm seeing:
<img width="699" alt="screen shot 2016-02-17 at 10 42 53 am" src="https://cloud.githubusercontent.com/assets/2466842/13120585/5246b14a-d563-11e5-9f70-8f7fe615e89e.png">
And when I delete the spacer rows using the element inspector:
<img width="699" alt="screen shot 2016-02-17 at 10 43 21 am" src="https://cloud.githubusercontent.com/assets/2466842/13120589/56dbde38-d563-11e5-8df6-388519c916b8.png">

**Comment by ryanlanciaux** [comment]
I think what we can do is in the spacer rows we can add a method like getColumns() that checks if width and fixed table is setup. If those conditions are met it would return something like

```
return Object.keys(this.props.renderProperties.columnProperties).map(k => (
  <td width={this.props.renderProperties.columnProperties[k].width}></td>)
)
```

or null. The <tr /> would need to instead be like `<tr>{ getColumns() }</tr>`
